name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Build and Test with Maven
      run: mvn test -Dbrowser=chrome -Dheadless=true

    - name: Archive test reports
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: target/surefire-reports