name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    # - name: Install Chrome
    #   run: |
    #     sudo apt update
    #     sudo apt install -y google-chrome-stable

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Set up Firefox
      uses: browser-actions/setup-firefox@latest

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew clean test -Denv=dev -Dbrowser=chrome -Dheadless=true --scan

    - name: Archive test reports
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: build/reports/tests/test
